version: '3.8'

services:
  oracle23c:
    image: gvenzl/oracle-free:23
    environment:
      - ORACLE_PASSWORD=123456
      - APP_USER=appuser
      - APP_USER_PASSWORD=123456
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
